analyzer/urls.py
from django.urls import path
from analyzer import views

app_name = 'analyzer'
urlpatterns = [
    path('', views.StatisticsView.as_view(), name='statistics'),
    path('suggestFriends/', views.SuggestFriendsView.as_view(), name='suggest_friends'),
    path('findOwner/', views.FindOwnerView.as_view(), name='find_owner'),
    path('currentUser/', views.CurrentUserStatsView.as_view(), name='current_user'),
    path('currentUser/<str:username>/<str:chart_name>/', views.ChartView.as_view(), name = 'chart' ),
    path('findOwnerResult/' , views.FindOwnerResultView.as_view(), name = 'find_owner_result')
]

chatanalyzer/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from analyzer.views import IndexView
import analyzer

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name = 'index'),
    path('statistics/', include('analyzer.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

analyzer/models.py
from django.db import models
from django.contrib.auth.models import User as BuiltinUser
from django.contrib.auth.validators import ASCIIUsernameValidator


class User(BuiltinUser):
    username_validator = ASCIIUsernameValidator()
    friend_list = models.CharField(max_length=2048, null = True)

class Message(models.Model):

    message_text = models.CharField(max_length=2048)
    sender = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='sender'
    )
    receiver = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='receiver'
    )
    date = models.DateTimeField(
        'written_date'
    )

    def __str__(self):
        return self.message_text

class UserStatistics(models.Model):
    def __str__(self):
        return "User " + self.user.username
    positivity_percentage = models.FloatField(null = True)
    avg_time = models.CharField(max_length=2048, null = True)
    avg_text_length = models.CharField(max_length=2048, null = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')

analyzer/views.py
import json
import urllib

from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic.base import View
from django.views.generic.list import ListView

from analyzer.models import UserStatistics, User
from analyzer.management.calculations.bestfriendcalculation import BestFriendCalculation
from analyzer.management.calculations.ownerfinder import OwnerFinder


default_length_dict = {'Very Short': 0, 'Short': 0, 'Medium': 0, 'Long': 0, 'Very Long': 0}


class IndexView(View):
    def get(self, request):
        return render(request, 'analyzer/index.html',
                      context={})
class StatisticsView(View):
    def get(self, request):
        return render(request, 'analyzer/statistics.html',
                      context={})


class SuggestFriendsView(View):
    def get(self, request):
        username = request.user.username
        calculator = BestFriendCalculation(3, username)
        suggestion_list = calculator.find_best_friends()
        return render(request, 'analyzer/suggest_friends.html',
                      context={'best_match': suggestion_list[0][0], 'suggestion_list': suggestion_list})


class FindOwnerView(ListView):
    def get(self, request):
        username = request.user.username
        return render(request, 'analyzer/find_owner.html')


class FindOwnerResultView(View):
    def get(self, request):
        message = urllib.parse.unquote(request.COOKIES['message_text'])
        (owner, confidence) = OwnerFinder.find_owner(message)
        if confidence == -1:
            return HttpResponse("unknown")
        return HttpResponse(owner)


class CurrentUserStatsView(ListView):
    def get(self, request):
        user_statistics = self.get_statistics_object(request)
        positivity_percentage = user_statistics.positivity_percentage
        return render(request, 'analyzer/current_user_stats.html',
                      context={'positivity_percentage': positivity_percentage})

    @staticmethod
    def get_statistics_object(request):
        username = request.user.username
        user = get_object_or_404(User, username=username)
        statistics = UserStatistics.objects.get(user=user)
        return statistics


class ChartView(View):
    def get(self, request, **kwargs):
        username = kwargs['username']
        user_statistics = self.get_statistics_object(username)
        table_data = {}
        default_data_list = [0, 0, 0, 0,
                             0]  # returns a data list of zeroes to chart for error handling (some of the user
        #  statistics in database might be null)
        if (kwargs['chart_name'] == 'time' and user_statistics.avg_time):
            table_data = json.loads(user_statistics.avg_time)

        elif (kwargs['chart_name'] == 'length' and user_statistics.avg_text_length):
            table_data = json.loads(user_statistics.avg_text_length)

        else:
            return HttpResponse(json.dumps(default_data_list))

        data_list = [table_data['Very Short'], table_data['Short'], table_data['Medium'], table_data['Long'],
                     table_data['Very Long']]
        return HttpResponse(json.dumps(data_list))

    @staticmethod
    def get_statistics_object(username):
        user = get_object_or_404(User, username=username)
        statistics = UserStatistics.objects.get(user=user)
        return statistics

templates/analyzer/current_user_stats.html
<head>
    {% load static %}
    <script src="{% static 'script/chart_ajax.js' %}"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <link rel = "stylesheet" type="text/css" href = "{% static 'css/statistics.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <script>
         var currentUser = "{%  url "analyzer:current_user" %}";
         var username = {{user.username}}
             $(document).ready(pageLoad);
    </script>

    <style>
        .w3-lobster{
            font-family: 'Lobster', serif;
            text-align: center;
            color: white;
            font-size: 32px;

        }

    </style>
</head>

<body>

    <div class="w3-container" style="margin-top:0px" id="showcase">
                    <h1 class="w3-half w3-lobster" style = 'text-align: left;color:#064752'><b>Statistics of {{user.username}}</b></h1>

    </div>

    <h6 class="btn w3-buttonColor w3-lobster" style="font-size:25px;margin:50px;"  onclick=" hide_show_length()" id = 'length_chart_button' >My message length statistics</h6>
    <h6 class="btn w3-buttonColor w3-lobster" style="font-size:25px;margin:50px;"  onclick="hide_show_time()" id = 'time_chart_button' >My answer time statistics</h6>
    <h6 class="btn w3-buttonColor w3-lobster" style="font-size:25px;margin:50px;"  onclick=" hide_show_positivity()" id = 'positivity_button' >How positive am I?</h6>

        <div id = "length" style = "width:300px;height:300px;top:50%;left:50%;">
            <div class = "col-sm-6" style="width:550px;height:550px;left:39%;position:absolute">
                <canvas id="lengthChart" width="100" height="100"></canvas>
            </div>
        </div>
        <div id = "time" style="top:50%;left:50%">
             <div class = "col-sm-6" style="width:550px;height:550px;left:39%;position:absolute">
                <canvas id="timeChart" width="100" height="100"></canvas>
            </div>
        </div>
        <div id = "positivity" style="top:100%;left:80%;">
            <h3 style = "top:30%;left:45%;position:absolute;border:5px solid #074954;border-radius:15px;color:#074954;width:300px;height:100px" class = "w3-lobster" >You are {{ positivity_percentage }}% positive!</h3>
        </div>

</body>

templates/analyzer/find_owner.html
<head>
    {% load static %}
    <script src="{% static 'script/find_owner.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'script/js.cookie.js' %}"></script>
    <script>
        var findOwnerResult = "{%  url "analyzer:find_owner_result" %}";
        $( document ).ready(function() {
            create_form();
        });
    </script>
</head>


<body>
    <div class="w3-container" style="margin-top:0px" id="showcase">
                    <h1 class="w3-half w3-lobster" style = 'text-align: left;color:#064752;'><b>Give us a sentence and we shall find who it belongs to!</b></h1>
    </div> <br><br><br><br><br><br>

    <div id = "form" >
    </div>
    <br>
    <h3 id = "result"></h3>

</body>

templates/analyzer/index.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

{% load static %}

<style>
    body{
        background-size:cover;
    }

</style>

<head>

    <link rel = "stylesheet" type="text/css" href = "{% static 'css/index.css' %}">
    <meta charset="UTF-8">
    <title>Chat</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

</head>
<body background={% static 'images/background.png' %}>
 <div style="text-align: center;" id = "sign">
        {% if user.username == "" %}
                <br><br>
                <h3>You are not logged in</h3>
                <a href="/accounts/login/" class = "btn btn-default btn-lg" role="button" id = "sign_in"><span class="glyphicon glyphicon-user"></span> Sign in </a>


        {% else %}
            <h2 style="font-style: oblique; color:#096388;">Welcome back {{user.username}}</h2>
            <br>

            <a href="statistics/" class = "btn btn-default btn-lg" role="button" id = "friends"><span class="glyphicon glyphicon-send"></span> Click to see your statistics </a>

            <br> <br> <br>
            <a href="/accounts/logout/" class = "btn btn-default btn-lg" role="button" id = "logout"><span class="glyphicon glyphicon-off"></span> Log Out </a>

        {% endif %}
   </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

templates/analyzer/statistics.html
<!DOCTYPE html>
<html>

<head>
{% load static %}
<script src="{% static 'script/chart_ajax.js' %}"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="{% static 'script/statistics_ajax.js' %}"></script>
 <script>
     var suggestFriends = "{% url "analyzer:suggest_friends" %}";
     var findOwner = "{% url "analyzer:find_owner" %}";
     var currentUser = "{%  url "analyzer:current_user" %}";
 </script>
<title>Statistics</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel = "stylesheet" type="text/css" href = "{% static 'css/statistics.css' %}">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<style>
    .w3-tangerine {
      font-family: 'Tangerine', serif;
      text-align: center;
    }
    .w3-lobster{
        font-family: 'Lobster', serif;
        text-align: center;
        color: white;
    }
    .w3-lobster:hover {
        color:white;

    }

    body{
        background-size:100%;
        background-repeat: no-repeat;
        background-attachment: fixed;
    }

}
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>


</head>
<body background={% static 'images/background.png' %}>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-mycolor w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:400px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="btn w3-buttonColor btn-block w3-lobster w3-hide-large w3-display-topleft" style="width:100%;font-size:25px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64 w3-tangerine" style = "font-size:60px;color:#063640;"><b>Here are your statistics {{user.first_name}}!</b></h3>

    <h6 class=" w3-tangerine" style = "font-size:50px;color:#0a5c6d"><b>Find your match</b></h6>

  </div>
  <h6 class="btn w3-buttonColor btn-block w3-lobster" style="font-size:25px;"  onclick=" change_tab_to_current_user_stats()" id = 'current_user_stats_button' >My Statistics</h6>
  <h6 class="btn w3-buttonColor btn-block w3-lobster" style="font-size:25px;"  onclick="change_tab_to_new_friends()" id = 'new_friend_button' >Find me new friends</h6>
  <h6 class="btn w3-buttonColor btn-block w3-lobster" style="font-size:25px;"  onclick=" change_tab_to_find_owner()" id = 'find_owner' >Write messages, find owners!</h6><br>

         <form action="/accounts/logout/" >
             <input type="submit" class="btn w3-buttonColor btn-block w3-lobster" style="font-size:25px;" value="Log out">
         </form>

</nav>

    <header class="w3-container w3-top w3-hide-large w3-mycolor w3-xlarge w3-padding">
      <a href="javascript:void(0)" class="w3-button w3-mycolor w3-margin-right" onclick="w3_open()">☰</a>
    </header>


    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
    <div class="w3-main" style="margin-left:400px;margin-right:40px">
             <div id = "statistics" style="padding:10px">

            </div>

    </div>




</body>




</html>

templates/analyzer/suggest_friends.html
<head>
  <script>
      var best_match ={{ best_match | safe}};
  </script>


</head>
<body>
    <div class="w3-container" style="margin-top:0px" id="showcase">
                    <h1 class="w3-half w3-lobster" style = 'text-align: left;color:#064752'><b>Best matches</b></h1>

    </div>
    {% if suggestion_list %}
        {% for percentage,friendName in suggestion_list %}
            <h3><span class="glyphicon glyphicon-fire" style = "color:pink"></span>You are {{ percentage }}% compatible with {{ friendName }}!</h3>

        {% endfor %}

    {% else %}
        <h3>Sorry we can't suggest any friends to you right now.</h3>
    {% endif %}
</body>